version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - 9000:9000
    networks:
      - laravel
    tty: true
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "/wait-for-it.sh laravel_db:3306 --timeout=60 --strict -- php artisan migrate && php artisan user:create-test && php-fpm"

  webserver:
    image: nginx:latest
    container_name: laravel_webserver
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - 3306:3306
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "laravel", "-plaravel"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  laravel:
    driver: bridge